on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: branch@master

      - uses: actions/cache@v5
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v6

      - name: Download Mod
        uses: actions/download-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: artifact

      - name: Copy additional files
        run: |
          cp -v LICENSE README.md artifact/

      - name: Archive release
        run: |
          zip -r ../${{ github.event.repository.name }}-windows-x64.zip *
        working-directory: artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ github.event.repository.name }}-windows-x64.zip