on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/DLL/

      - uses: actions/upload-artifact@v3
        with:
          name: PDB
          path: |
            bin/PDB/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Plugin
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: release/Plugin/

      - name: Download PDB
        uses: actions/download-artifact@v3
        with:
          name: PDB
          path: release/PDB/

      - name: Copy additional files
        run: |
          cp LICENSE README.md release/Plugin/

      - name: Archive release
        run: |
          cd release/Plugin
          zip -r ../${{ github.event.repository.name }}-windows-x64.zip *
          cd ..

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/${{ github.event.repository.name }}-windows-x64.zip
            release/PDB/${{ github.event.repository.name }}.pdb 
